/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
*/

import React, { useRef, useMemo, memo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";
import * as THREE from "three";
import { usePerformance } from "../../context/PerformanceContext";

export const Room = memo(function Room(props) {
  const { nodes, materials } = useGLTF("/models/optimized-room.glb");
  const screensRef = useRef();
  const matcapTexture = useTexture("/images/textures/mat1.png");

  const { settings, isLowTier, isHighTier, viewport } = usePerformance();
  const { isMobile, isTablet } = viewport;

  // Use useMemo to create materials only once
  // Material quality is now based on GPU tier, not just viewport size
  const memoizedMaterials = useMemo(() => {
    // Use simpler materials on low-tier devices
    const MaterialClass = settings.useLowPolyMaterials
      ? THREE.MeshBasicMaterial
      : THREE.MeshPhongMaterial;

    return {
      curtainMaterial: new MaterialClass({
        color: "#d90429",
      }),
      bodyMaterial: new MaterialClass({
        map: matcapTexture,
      }),
      tableMaterial: new MaterialClass({
        color: "#582f0e",
      }),
      radiatorMaterial: new MaterialClass({
        color: "#fff",
      }),
      compMaterial: new MaterialClass({
        color: "#fff",
      }),
      pillowMaterial: new MaterialClass({
        color: "#8338ec",
      }),
      chairMaterial: new MaterialClass({
        color: "#000",
      }),
    };
  }, [matcapTexture, settings.useLowPolyMaterials]);

  // Create shared instance material to reduce draw calls
  const sharedMaterial = useMemo(() => {
    return materials.blinn1.clone();
  }, [materials.blinn1]);

  // Only render bloom on HIGH tier devices (not just desktop)
  const shouldRenderBloom = settings.enableBloom && isHighTier && !isTablet;

  return (
    <group {...props} dispose={null}>
      {/* Only add post-processing effects on high-tier desktop devices */}
      {shouldRenderBloom && (
        <EffectComposer enabled={true} multisampling={0}>
          <SelectiveBloom
            selection={screensRef}
            intensity={1.2}
            luminanceThreshold={0.25}
            luminanceSmoothing={0.9}
            blendFunction={BlendFunction.ADD}
            // Lower resolution for bloom to improve performance
            mipmapBlur
            radius={0.6}
          />
        </EffectComposer>
      )}

      <mesh
        geometry={nodes._________6_blinn1_0.geometry}
        material={memoizedMaterials.curtainMaterial}
      />
      <mesh
        geometry={nodes.body1_blinn1_0.geometry}
        material={memoizedMaterials.bodyMaterial}
      />
      <mesh
        geometry={nodes.cabin_blinn1_0.geometry}
        material={memoizedMaterials.tableMaterial}
      />
      <mesh
        geometry={nodes.chair_body_blinn1_0.geometry}
        material={memoizedMaterials.chairMaterial}
      />
      <mesh
        geometry={nodes.comp_blinn1_0.geometry}
        material={memoizedMaterials.compMaterial}
      />
      <mesh
        ref={screensRef}
        geometry={nodes.emis_lambert1_0.geometry}
        material={materials.lambert1}
      />

      {/* Use shared material for less important objects to reduce draw calls */}
      <mesh
        geometry={nodes.handls_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.keyboard_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.kovrik_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.lamp_bl_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.lamp_white_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.miuse_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.monitor2_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.monitor3_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.pCylinder5_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.pillows_blinn1_0.geometry}
        material={memoizedMaterials.pillowMaterial}
      />
      <mesh
        geometry={nodes.polySurface53_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.radiator_blinn1_0.geometry}
        material={memoizedMaterials.radiatorMaterial}
      />
      <mesh
        geometry={nodes.radiator_blinn1_0001.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.railing_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.red_bttns_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.red_vac_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.stylus_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.table_blinn1_0.geometry}
        material={memoizedMaterials.tableMaterial}
      />
      <mesh
        geometry={nodes.tablet_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.triangle_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.vac_black_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.vacuum1_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.vacuumgrey_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.vires_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.window_blinn1_0.geometry}
        material={sharedMaterial}
      />
      <mesh
        geometry={nodes.window4_phong1_0.geometry}
        material={materials.phong1}
      />
    </group>
  );
});

useGLTF.preload("/models/optimized-room.glb");

